spring.application.name=sportify

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sportify
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=Y.VirajKshithiz
spring.datasource.password=

# Let Hibernate auto-create tables from our entities (fine for dev; we'll
# switch to managed migrations like Flyway before this matters for prod)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

jwt.secret=ThisIsADevelopmentOnlySecretKeyPleaseReplaceInProduction1234567890
jwt.expiration-ms=86400000
